Acronym
annaoliinyk/SoftServe-Internship_python pull request #16
Opened 2022-08-25 07:35 UTC by annaoliinyk

https://exercism.org/tracks/python/exercises/acronym

Instructions
Convert a phrase to its acronym.

Techies love their TLA (Three Letter Acronyms)!

Help generate some jargon by writing a program that converts a long name like Portable Network Graphics to its acronym (PNG).

Punctuation is handled as follows: hyphens are word separators (like whitespace); all other punctuation can be removed from the input.

2022-09-05 20:35 UTC, AnnieKey commented on acronym/acronym_task.py
> +def split_phrase_into_list_words(phrase):
Name is too long

2022-09-05 20:39 UTC, AnnieKey commented on acronym/acronym_task.py
> +    phrase = phrase.replace("  ", " ")
It is not effective. You're iterating phrase 4 times from the beginning till the end.

2022-09-05 20:39 UTC, AnnieKey requested changes
Please change what was requested

2022-09-09 07:47 UTC, annaoliinyk commented
Fixed

2022-09-09 10:17 UTC, AnnieKey approved these changes

2022-09-09 10:50 UTC, merged