Protein translation
annaoliinyk/SoftServe-Internship_python pull request #17
Opened 2022-08-25 07:39 UTC by annaoliinyk

https://exercism.org/tracks/python/exercises/protein-translation

2022-09-05 20:34 UTC, AnnieKey commented on protein_translation/protein_translation_task.py
> +        }
Put it into separate constant outside the function

2022-09-05 20:34 UTC, AnnieKey commented on protein_translation/protein_translation_task.py
> +        if codon in ["UAA", "UAG", "UGA"]:
Put this list in a constant outside the function

2022-09-05 20:35 UTC, AnnieKey requested changes
Please change what was commented above

2022-09-09 07:07 UTC, annaoliinyk commented
Added main(), logging and renamed constants

2022-09-09 10:16 UTC, AnnieKey approved these changes

2022-09-09 10:50 UTC, merged