Added a task Atbash Cipher
annaoliinyk/SoftServe-Internship_python pull request #20
Opened 2022-08-25 14:07 UTC by annaoliinyk

https://exercism.org/tracks/python/exercises/atbash-cipher

Instructions
Create an implementation of the atbash cipher, an ancient encryption system created in the Middle East.

The Atbash cipher is a simple substitution cipher that relies on transposing all the letters in the alphabet such that the resulting alphabet is backwards. The first letter is replaced with the last letter, the second with the second-last, and so on.

An Atbash cipher for the Latin alphabet would be as follows:

Plain:  abcdefghijklmnopqrstuvwxyz
Cipher: zyxwvutsrqponmlkjihgfedcba
It is a very weak cipher because it only has one possible key, and it is a simple mono-alphabetic substitution cipher. However, this may not have been an issue in the cipher's time.

Ciphertext is written out in groups of fixed length, the traditional group size being 5 letters, leaving numbers unchanged, and punctuation is excluded. This is to make it harder to guess things based on word boundaries.

Examples
- Encoding test gives gvhg
- Encoding x123 yes gives c123b vh
- Decoding gvhg gives test
- Decoding gsvjf rxpyi ldmul cqfnk hlevi gsvoz abwlt gives thequickbrownfoxjumpsoverthelazydog

2022-09-05 20:27 UTC, AnaKovaGH commented on atbash_cipher/atbash_cipher_task.py
> +    cipher_str = "zyxwvutsrqpon0123456789mlkjihgfedcba"
Make it separate constant outside the function

2022-09-05 20:28 UTC, AnnieKey commented on atbash_cipher/atbash_cipher_task.py
> +    cipher_str = "zyxwvutsrqpon0123456789mlkjihgfedcba"
Same here

2022-09-05 20:30 UTC, AnnieKey commented on atbash_cipher/atbash_cipher_task.py
> +        if symbol in plain_str:
Please change these if statement as it has the same condition as in previous one

2022-09-05 20:32 UTC, AnnieKey commented on atbash_cipher/atbash_cipher_task.py
> +            result += plain_str[index]
Lines 25 and 26 looks quite similar to 13 and 14. Maybe there is a reason why it should be in separate function?

2022-09-05 20:33 UTC, AnnieKey requested changes
Please change what was commented above.

2022-09-07 10:47 UTC, annaoliinyk commented
The issues were fixed, simplified program readability, added main() method and logging

2022-09-08 17:57 UTC, annaoliinyk commented
made constants uppercase, changed logging from debug to info

2022-09-09 10:15 UTC, AnnieKey approved these changes

2022-09-09 10:50 UTC, merged