Grep
annaoliinyk/SoftServe-Internship_python pull request #21
Opened 2022-08-26 13:16 UTC by annaoliinyk

https://exercism.org/tracks/python/exercises/grep

Search a file for lines matching a regular expression pattern. Return the line number and contents of each matching line.

Implement the Unix grep command

2022-09-05 20:22 UTC, AnnieKey commented on grep/grep_task.py
> +
there is no need for this space

2022-09-05 20:24 UTC, AnnieKey commented on grep/grep_task.py
> +            datafile = get_data_from_file(files[i])
Why do you open file with every loop run?

2022-09-05 20:25 UTC, AnnieKey commented on grep/grep_task.py
> +                if "-i" in flags:
Remove hardcoded values here. Make a separate constant outside with all this values.

2022-09-05 20:26 UTC, AnnieKey requested changes
Please also change that mane if-else statements

2022-09-09 13:50 UTC, annaoliinyk commented
Added files needed for tests (from excercism)

2022-09-09 15:16 UTC, annaoliinyk commented
Ready for review

2022-09-10 12:47 UTC, AnnieKey requested changes
Could you please get rid of binary files. They should be in gitignore.

2022-09-12 07:44 UTC, annaoliinyk commented
Fixed

2022-09-13 11:59 UTC, AnnieKey approved these changes

2022-09-13 12:37 UTC, merged