Sublist
annaoliinyk/SoftServe-Internship_python pull request #22
Opened 2022-08-26 13:53 UTC by annaoliinyk

https://exercism.org/tracks/python/exercises/sublist

Instructions
Given any two lists A and B, determine if:

- List A is equal to list B; or
- List A contains list B (A is a superlist of B); or
- List A is contained by list B (A is a sublist of B); or
- None of the above is true, thus lists A and B are unequal

Specifically, list A is equal to list B if both lists have the same values in the same order. List A is a superlist of B if A contains a sub-sequence of values equal to B. List A is a sublist of B if B contains a sub-sequence of values equal to A.

2022-09-05 20:18 UTC, AnnieKey commented on sublist/sublist_task.py
> +def check_if_all_items_in_full_list(full_list, sub_list):
Too long function name

2022-09-05 20:18 UTC, AnnieKey commented on sublist/sublist_task.py
> +UNEQUAL = 4
Where do you use this constants?

2022-09-05 20:19 UTC, AnnieKey commented on sublist/sublist_task.py
> +    return sub_list_as_str in full_list_as_str and check_if_all_items_in_full_list(full_list, sub_list)
It is too hard to understand, please re-write it. How it works?

2022-09-05 20:19 UTC, AnnieKey approved these changes, later dismissed

2022-09-05 20:21 UTC, AnnieKey requested changes
Please change what was commented.

2022-09-06 14:49 UTC, annaoliinyk commented
Re-wrote the solution

2022-09-07 12:24 UTC, AnnieKey requested changes
Please check how to work with sublist(["a", "d", "a", "s"], ["a", "a", "a"])

2022-09-08 12:46 UTC, annaoliinyk commented
This was fixed

2022-09-09 10:15 UTC, AnnieKey approved these changes

2022-09-09 10:50 UTC, merged