Added a Leap task
annaoliinyk/SoftServe-Internship_python pull request #25
Opened 2022-08-30 09:47 UTC by annaoliinyk

Instructions
Given a year, report if it is a leap year.

The tricky thing here is that a leap year in the Gregorian calendar occurs:

on every year that is evenly divisible by 4
  except every year that is evenly divisible by 100
    unless the year is also evenly divisible by 400
For example, 1997 is not a leap year, but 1996 is. 1900 is not a leap year, but 2000 is.

Source: https://exercism.org/tracks/python/exercises/leap

2022-09-05 20:05 UTC, AnnieKey requested changes
Please re-write without if-else structure

2022-09-06 12:12 UTC, AnnieKey requested changes
Please change print to logger

2022-09-08 12:51 UTC, annaoliinyk commented
Fixed

2022-09-09 10:12 UTC, AnnieKey approved these changes

2022-09-09 10:49 UTC, merged