Added a Resistor Color Duo task
annaoliinyk/SoftServe-Internship_python pull request #26
Opened 2022-08-30 10:24 UTC by annaoliinyk

https://exercism.org/tracks/python/exercises/resistor-color-duo

Instructions
If you want to build something using a Raspberry Pi, you'll probably use resistors. For this exercise, you need to know two things about them:

Each resistor has a resistance value.
Resistors are small - so small in fact that if you printed the resistance value on them, it would be hard to read.
To get around this problem, manufacturers print color-coded bands onto the resistors to denote their resistance values. Each band has a position and a numeric value.

The first 2 bands of a resistor have a simple encoding scheme: each color maps to a single number. For example, if they printed a brown band (value 1) followed by a green band (value 5), it would translate to the number 15.

In this exercise you are going to create a helpful program so that you don't have to remember the values of the bands. The program will take color names as input and output a two digit number, even if the input is more than two colors!

The band colors are encoded as follows:

Black: 0
Brown: 1
Red: 2
Orange: 3
Yellow: 4
Green: 5
Blue: 6
Violet: 7
Grey: 8
White: 9
From the example above: brown-green should return 15 brown-green-violet should return 15 too, ignoring the third color.

2022-09-05 20:01 UTC, AnnieKey requested changes
Please make the dict constant structure outside the function

2022-09-07 10:10 UTC, annaoliinyk commented
Fixed

2022-09-07 12:07 UTC, AnnieKey commented on resistor_color_duo/resistor_color_duo_task.py
> +switch = {
Constants should be written in upper case

2022-09-07 12:15 UTC, AnnieKey commented on resistor_color_duo/resistor_color_duo_task.py
> +    logging.debug(value(["red"]))
Change DEBUG to INFO

2022-09-07 12:15 UTC, AnnieKey requested changes
Please change what was mentioned

2022-09-08 11:58 UTC, annaoliinyk commented
Fixed

2022-09-08 12:02 UTC, AnnieKey approved these changes

2022-09-08 12:28 UTC, merged