Added a task pangram
annaoliinyk/SoftServe-Internship_python pull request #5
Opened 2022-08-19 14:03 UTC by annaoliinyk

https://exercism.org/tracks/python/exercises/pangram

Instructions
Determine if a sentence is a pangram. A pangram (Greek: παν γράμμα, pan gramma, "every letter") is a sentence using every letter of the alphabet at least once. The best known English pangram is:

The quick brown fox jumps over the lazy dog.

The alphabet used consists of letters a to z, inclusive, and is case insensitive.

2022-09-05 21:00 UTC, AnnieKey commented on pangram/pangram_file.py
> +    alphabet = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u',
It should be constant

2022-09-05 21:00 UTC, AnnieKey requested changes
Please change what was requested above

2022-09-06 12:06 UTC, AnnieKey commented on pangram/pangram_file.py
> +    print(is_pangram('a quick movement of the enemy will jeopardize five gunboats'))
Please change print to logger output

2022-09-06 12:07 UTC, AnnieKey requested changes
Please change print to logger

2022-09-09 12:05 UTC, annaoliinyk commented
Ready for review

2022-09-10 13:05 UTC, AnnieKey approved these changes

2022-09-11 13:21 UTC, merged