Added a task Bob
annaoliinyk/SoftServe-Internship_python pull request #6
Opened 2022-08-19 14:04 UTC by annaoliinyk

https://exercism.org/tracks/python/exercises/bob

Instructions
Bob is a lackadaisical teenager. In conversation, his responses are very limited.

Bob answers 'Sure.' if you ask him a question, such as "How are you?".

He answers 'Whoa, chill out!' if you YELL AT HIM (in all capitals).

He answers 'Calm down, I know what I'm doing!' if you yell a question at him.

He says 'Fine. Be that way!' if you address him without actually saying anything.

He answers 'Whatever.' to anything else.

Bob's conversational partner is a purist when it comes to written communication and always follows normal rules regarding sentence punctuation in English.

2022-09-05 20:58 UTC, AnnieKey commented on bob/bob_task.py
> +
Unnecessary space

2022-09-05 20:59 UTC, AnnieKey commented on bob/bob_task.py
> +        return 'Fine. Be that way!'
Please choose one rule regarding quotation marks and use it everywhere in the code

2022-09-05 21:00 UTC, AnnieKey requested changes
Please change what was requested above

2022-09-06 07:51 UTC, annaoliinyk commented
This was fixed

2022-09-09 11:57 UTC, annaoliinyk commented
Ready for review

2022-09-10 13:05 UTC, AnnieKey requested changes
Please remove hard-coded values in the return statements (e.g. return POSSIBLE_ANSWERS[2]), use dictionary instead.
This this bad approach, because in case if you change the order or add new answers to the list, the logic will be broken.

2022-09-12 08:29 UTC, annaoliinyk commented
Done

2022-09-13 12:00 UTC, AnnieKey approved these changes

2022-09-13 12:40 UTC, merged