Rna transcription
annaoliinyk/SoftServe-Internship_python pull request #9
Opened 2022-08-23 14:25 UTC by annaoliinyk

Instructions
Given a DNA strand, return its RNA complement (per RNA transcription).

Both DNA and RNA strands are a sequence of nucleotides.

The four nucleotides found in DNA are adenine (A), cytosine (C), guanine (G) and thymine (T).

The four nucleotides found in RNA are adenine (A), cytosine (C), guanine (G) and uracil (U).

Given a DNA strand, its transcribed RNA strand is formed by replacing each nucleotide with its complement:

G -> C
C -> G
T -> A
A -> U

2022-09-05 20:54 UTC, AnnieKey commented on rna_transcription/rna_transcription_task.py
> +        result += switch.get(letter, "")
What if letter will be in lower case?

2022-09-05 20:55 UTC, AnnieKey requested changes
Please change what was requested

2022-09-09 11:25 UTC, annaoliinyk commented
Fixed

2022-09-10 12:59 UTC, AnnieKey approved these changes

2022-09-11 13:31 UTC, merged